### ISSUE TITLE
About the Heaviside DIC

### ISSUE THREAD

**Issue by Cra2yDavid** [charpagne/slipAnalysis#2]
I noticed that you mentioned Heaviside DIC algorithm and it can be combined with this slipAnalysis program. Could you please share some implementation code of Heaviside DIC with me? Thanks a lot!

**Comment by charpagne** [comment]
David, do you mean the Heaviside code?

**Comment by Cra2yDavid** [comment]
Yes, I want to use Heaviside DIC mothed to analyse the slip data for my graduation project. However, it is quit difficult for me to reproduce such code.

**Comment by charpagne** [comment]
I can't do that sorry. Developping this kind of code is not a grad project at all and takes many years in someone's career to develop. You won't find this kind of code in github.

**Comment by Cra2yDavid** [comment]
I get it. Anyway, thanks for your generous reply.
